export const actionTypesCart = {
  PRODUCT_INTO_CART_START: "ADD_PRODUCT_INTO_CART_START",
  ADD_PRODUCT_INTO_CART_SUCCESS: "ADD_PRODUCT_INTO_CART_SUCCESS",
  DELETE_PRODUCT_INTO_CART_SUCCESS: "DELETE_PRODUCT_INTO_CART_SUCCESS",
  PRODUCT_INTO_CART_ERROR: "ADD_PRODUCT_INTO_CART_START",
  DECRASE_QUANTINTY_PRODUCTS: "DECRASE_QUANTINTY_PRODUCTS",
  SUMMARY_QUANTITY_PRODUCT_INTO_CART: "SUMMARY_QUANTITY_PRODUCT_INTO_CART",
};
