export const actionTypesCart = {
  PRODUCT_INTO_CART_START: "ADD_PRODUCT_INTO_CART_START",
  ADD_PRODUCT_INTO_CART_SUCCESS: "ADD_PRODUCT_INTO_CART_SUCCESS",
  DELETE_PRODUCT_INTO_CART_SUCCESS: "DELETE_PRODUCT_INTO_CART_SUCCESS",
  PRODUCT_INTO_CART_ERROR: "ADD_PRODUCT_INTO_CART_START",
};
